### ISSUE TITLE
Error while trying to update One CLI to latest version

### ISSUE THREAD

**Issue by sohflp** [DNXLabs/one-cli#97]
### Issue Summary

While trying to update the One CLI I received the following error:

```
Plataform: darwin
Updating CLI...
Traceback (most recent call last):
  File "site-packages/docker/client.py", line 170, in _raise_for_status
  File "site-packages/requests/models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.24/images/create?tag=latest&fromImage=dnxsolutions%2Fone-cli-update

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 5, in <module>
  File "one/__main__.py", line 5, in main
  File "site-packages/click/core.py", line 829, in __call__
  File "site-packages/click/core.py", line 782, in main
  File "site-packages/click/core.py", line 1259, in invoke
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 610, in invoke
  File "one/commands/update.py", line 21, in update
  File "one/docker/container.py", line 15, in create
  File "one/docker/image.py", line 54, in check_image
  File "one/docker/image.py", line 57, in pull
  File "site-packages/docker/api/image.py", line 175, in pull
  File "site-packages/docker/client.py", line 173, in _raise_for_status
docker.errors.NotFound: 404 Client Error: Not Found ("b'{"message":"pull access denied for dnxsolutions/one-cli-update, repository does not exist or may require \'docker login\': denied: requested access to the resource is denied"}'")
[94678] Failed to execute script cli
```

## Steps to Reproduce the Problem

  1. Try to update the CLI with the command `one update`.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

## Specifications

  - Version: **one, version 0.5.1**
  - Platform: **macOS**
  - Installation method: **Binary**

**Comment by arthurbdiniz** [comment]
Hi @sohflp, this `one update` command was removed since [0.6.0](https://github.com/DNXLabs/one-cli/releases/tag/0.6.0) release.
